# Introduction

## Introduction

This course builds on the original [Introduction to R training course](https://github.com/moj-analytical-services/IntroRTraining), and covers additional programming concepts. It provides examples that demonstrate how the Tidyverse packages can assist with tasks typically encountered in MoJ Data & Analysis.

Development of the Tidyverse suite of packages was led by Hadley Wickham, and more information about these packages can be found on the [Tidyverse website](https://www.tidyverse.org/) as well as in the book [R for Data Science](https://r4ds.had.co.nz/).

The first two chapters of this course cover two fundamentals of programming in R: conditional statements and loops. These two topics come under the umbrella of 'control flow', which refers to how we can change the order that pieces of code are run in. With conditional statements we can introduce choices, where different pieces of code are run depending on the input, and loops allow us to repeatedly run the same piece of code.

## Learning outcomes

### By the end of this session you should know how to:

 - Change what the code does based on a condition
 - Classify values in a dataframe, based on a set of conditions
 - Read and combine data from multiple csv files
 - Easily apply a function to multiple columns in a dataframe
 - Deal with missing values in a dataframe
 - Reshape dataframes
 - Search for a string pattern in a dataframe


## Before we start

To follow along with the code and participate in the exercises, open the script "example_code.R" in RStudio. All the code that we'll show in this session is stored in "example_code.R", and you can edit this script to write solutions to the exercises. You may also want to have the course [README](https://github.com/moj-analytical-services/intro_r_training_extension) open as a reference.

First, we need to load a few packages:

```{r message=F, warning=F, purl=purl_example_code}
# Load packages
library(botor) # Used to help R interact with s3 cloud storage
library(dplyr) # Used for data manipulation
library(tidyr) # Used to help reshape and deal with missing data
library(stringr) # Used for string manipulation
library(readr) # Used to help read in data
```

